version: '3'
services:
#    nginx:
#        image: nginx:latest
#        container_name: nginx0
#        ports:
#            - "8000:8000"
#        volumes:
#            - ./api-server:/api-server
#            - ./web-app:/web-app
#            - ./config/nginx:/etc/nginx/conf.d
#        depends_on:
#            - web
    gunicorn:
        image: foodtruck_api
        build:
            context: .
            dockerfile: ./docker/gunicorn/Dockerfile
        depends_on:
            - redis
        ports:
            - "8000:8000"
#        volumes:
#            - ./api-server/:/src
    cron:
        image: foodtruck_cron
        build:
            context: .
            dockerfile: ./docker/cron/Dockerfile
#        volumes:
#            - ./api-server/:/src
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
