version: '2'
services:
    gunicorn:
        image: foodtruck_api
        build:
            context: .
            dockerfile: ./docker/gunicorn/Dockerfile
        depends_on:
            - redis
        ports:
            - "8000:8000"
        volumes:
            - ./api-server/:/src
    cron:
        image: foodtruck_cron
        build:
            context: .
            dockerfile: ./docker/cron/Dockerfile
#        volumes:
#            - ./api-server/:/src
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"


    nginx:
        build: docker/nginx/
        container_name: ng01
        ports:
            - "80:80"
        depends_on:
            - gunicorn
        volumes:
            - ./web-app/:/usr/share/nginx/html

    test:
        image: foodtruck_test
        build:
            context: .
            dockerfile: ./docker/pyresttest/Dockerfile
        depends_on:
            - nginx
        volumes:
            - ./api-server/tests/:/tests/
        command: sh -c "sleep 10 ; pyresttest http://nginx:80 integration/httpbin.yaml"

