redis:
    host: redis
    port: 6379
    db_num: 0
db_keys:
    truck_geo_data_key: "TRUCKS_POSITIONS"

datasets:
    trucks: https://data.sfgov.org/resource/6a9r-agq8.json
    schedules: https://data.sfgov.org/resource/bbb8-hzi6.json

datasets_local:
    trucks: data/rqzj-sfat.json
    schedules: data/bbb8-hzi6.json
    cuisines: data/cuisines_food_items_matching.yml
